const indianCities = [
  "Mumbai, Maharashtra",
  "Pune, Maharashtra",
  "Nagpur, Maharashtra",
  "Nashik, Maharashtra",
  "Aurangabad, Maharashtra",
  "Delhi, Delhi",
  "Bengaluru, Karnataka",
  "Mysuru, Karnataka",
  "Chennai, Tamil Nadu",
  "Coimbatore, Tamil Nadu",
  "Madurai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Surat, Gujarat",
  "Vadodara, Gujarat",
  "Rajkot, Gujarat",
  "Jaipur, Rajasthan",
  "Jodhpur, Rajasthan",
  "Udaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Agra, Uttar Pradesh",
  "Varanasi, Uttar Pradesh",
  "Ghaziabad, Uttar Pradesh",
  "Noida, Uttar Pradesh",
  "Indore, Madhya Pradesh",
  "Bhopal, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Jabalpur, Madhya Pradesh",
  "Patna, Bihar",
  "Gaya, Bihar",
  "Bhagalpur, Bihar",
  "Visakhapatnam, Andhra Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Guntur, Andhra Pradesh",
  "Nellore, Andhra Pradesh",
  "Ludhiana, Punjab",
  "Amritsar, Punjab",
  "Jalandhar, Punjab",
  "Chandigarh, Chandigarh",
  "Kochi, Kerala",
  "Thiruvananthapuram, Kerala",
  "Kozhikode, Kerala",
  "Ranchi, Jharkhand",
  "Jamshedpur, Jharkhand",
  "Bhubaneswar, Odisha",
  "Cuttack, Odisha",
  "Dehradun, Uttarakhand",
  "Haridwar, Uttarakhand",
  "Shimla, Himachal Pradesh",
  "Dharamshala, Himachal Pradesh",
  "Guwahati, Assam",
  "Silchar, Assam",
  "Shillong, Meghalaya",
  "Aizawl, Mizoram",
  "Imphal, Manipur",
  "Agartala, Tripura",
  "Itanagar, Arunachal Pradesh",
  "Panaji, Goa",
  "Puducherry, Puducherry",
  "Port Blair, Andaman and Nicobar Islands",
  "Daman, Dadra and Nagar Haveli and Daman and Diu",
  "Kavaratti, Lakshadweep"
];

  
  export default indianCities;